"""remove first_last_name

Revision ID: fd073bc2e4ed
Revises: 44c07c1f8d63
Create Date: 2023-01-05 11:51:04.040693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd073bc2e4ed'
down_revision = '44c07c1f8d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
